// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nebula.Server.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nebula.Server.Migrations
{
    [DbContext(typeof(NebulaDbContext))]
    [Migration("20260926143143_AddSyndicatePass")]
    partial class AddSyndicatePass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nebula.Domain.Entities.CosmeticItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceInCoins")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CosmeticItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetRef = "drone-neon-crimson",
                            Description = "A red neon glowing drone skin.",
                            Name = "Neon Crimson",
                            PriceInCoins = 500,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            AssetRef = "avatar-gold-elite",
                            Description = "Premium gold plated avatar.",
                            Name = "Gold Elite",
                            PriceInCoins = 1000,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VaultCredits")
                        .HasColumnType("integer");

                    b.Property<int>("VaultIronium")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.MatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalStateJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("ParticipantIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("ReplayDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MatchRecords");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.PlayerClaimedReward", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeasonTierId")
                        .HasColumnType("integer");

                    b.Property<bool>("ClaimedFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("ClaimedPremium")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "SeasonTierId");

                    b.ToTable("PlayerClaimedRewards");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.PlayerCosmetic", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("CosmeticItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "CosmeticItemId");

                    b.HasIndex("CosmeticItemId");

                    b.ToTable("PlayerCosmetics");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PremiumCredits")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.PlayerQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDateUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardCredits")
                        .HasColumnType("integer");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PlayerQuests");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.PlayerSeasonProgress", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasPremiumPass")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalXP")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "SeasonId");

                    b.ToTable("PlayerSeasonProgress");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.PremiumLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PremiumLedgerEntries");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDateUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDateUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.SeasonTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FreeCosmeticId")
                        .HasColumnType("integer");

                    b.Property<int?>("PremiumCosmeticId")
                        .HasColumnType("integer");

                    b.Property<int>("PremiumCurrencyReward")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredXP")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonTiers");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.PlayerCosmetic", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.CosmeticItem", "Item")
                        .WithMany()
                        .HasForeignKey("CosmeticItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.PlayerProfile", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.PlayerProfile", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.PremiumLedgerEntry", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.PlayerProfile", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.SeasonTier", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Season", null)
                        .WithMany("Tiers")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Guild", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Season", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
