// File: Nebula.Shared/Models/ChatMessage.cs
namespace Nebula.Shared.Models
{
    public class ChatMessage
    {
        public string SenderName { get; set; } = string.Empty;
        public string Message { get; set; } = string.Empty;
        public string Channel { get; set; } = string.Empty; // "Global" or "Match"
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
        public bool IsSystemEvent { get; set; } // True if generated by the server, not a player
    }
}
